const tilesData = [
  { src: '/manzu2_1/p_ms1_1.gif', label: 'm1' },
  { src: '/manzu2_1/p_ms2_1.gif', label: 'm2' },
  { src: '/manzu2_1/p_ms3_1.gif', label: 'm3' },
  { src: '/manzu2_1/p_ms4_1.gif', label: 'm4' },
  { src: '/manzu2_1/p_ms5_1.gif', label: 'm5' },
  { src: '/manzu2_1/p_ms6_1.gif', label: 'm6' },
  { src: '/manzu2_1/p_ms7_1.gif', label: 'm7' },
  { src: '/manzu2_1/p_ms8_1.gif', label: 'm8' },
  { src: '/manzu2_1/p_ms9_1.gif', label: 'm9' },
  { src: '/pinzu2_1/p_ps1_1.gif', label: 'p1' },
  { src: '/pinzu2_1/p_ps2_1.gif', label: 'p2' },
  { src: '/pinzu2_1/p_ps3_1.gif', label: 'p3' },
  { src: '/pinzu2_1/p_ps4_1.gif', label: 'p4' },
  { src: '/pinzu2_1/p_ps5_1.gif', label: 'p5' },
  { src: '/pinzu2_1/p_ps6_1.gif', label: 'p6' },
  { src: '/pinzu2_1/p_ps7_1.gif', label: 'p7' },
  { src: '/pinzu2_1/p_ps8_1.gif', label: 'p8' },
  { src: '/pinzu2_1/p_ps9_1.gif', label: 'p9' },
  { src: '/sozu2_1/p_ss1_1.gif', label: 's1' },
  { src: '/sozu2_1/p_ss2_1.gif', label: 's2' },
  { src: '/sozu2_1/p_ss3_1.gif', label: 's3' },
  { src: '/sozu2_1/p_ss4_1.gif', label: 's4' },
  { src: '/sozu2_1/p_ss5_1.gif', label: 's5' },
  { src: '/sozu2_1/p_ss6_1.gif', label: 's6' },
  { src: '/sozu2_1/p_ss7_1.gif', label: 's7' },
  { src: '/sozu2_1/p_ss8_1.gif', label: 's8' },
  { src: '/sozu2_1/p_ss9_1.gif', label: 's9' },
  { src: '/tupai2_1/p_ji_c_1.gif', label: 'chun' },
  { src: '/tupai2_1/p_ji_e_1.gif', label: 'east' },
  { src: '/tupai2_1/p_ji_h_1.gif', label: 'hatsu' },
  { src: '/tupai2_1/p_ji_n_1.gif', label: 'north' },
  { src: '/tupai2_1/p_ji_s_1.gif', label: 'south' },
  { src: '/tupai2_1/p_ji_w_1.gif', label: 'west' },
  { src: '/tupai2_1/p_no_1.gif', label: 'haku' }
];

  export default tilesData;